
package views;

public class FrmMain extends javax.swing.JFrame {

    public FrmMain() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LblIcono = new javax.swing.JLabel();
        LblUserFullname = new javax.swing.JLabel();
        BarMenu = new javax.swing.JMenuBar();
        MnuFile = new javax.swing.JMenu();
        MnuFileUsers = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        MnuFileLogout = new javax.swing.JMenuItem();
        MnuTest = new javax.swing.JMenu();
        MnuTestResponse = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        MnuTestSetting = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de evaluación");
        setResizable(false);

        LblIcono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/evaluacion.png"))); // NOI18N

        LblUserFullname.setText("Estudiante: Docente....");

        MnuFile.setText("Archivo");

        MnuFileUsers.setText("Usuarios");
        MnuFileUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnuFileUsersActionPerformed(evt);
            }
        });
        MnuFile.add(MnuFileUsers);
        MnuFile.add(jSeparator2);

        MnuFileLogout.setText("Salir");
        MnuFileLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnuFileLogoutActionPerformed(evt);
            }
        });
        MnuFile.add(MnuFileLogout);

        BarMenu.add(MnuFile);

        MnuTest.setText("Encuestas");

        MnuTestResponse.setText("Responder");
        MnuTest.add(MnuTestResponse);
        MnuTest.add(jSeparator1);

        MnuTestSetting.setText("Configurar");
        MnuTest.add(MnuTestSetting);

        BarMenu.add(MnuTest);

        setJMenuBar(BarMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(LblIcono))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(LblUserFullname)))
                .addContainerGap(141, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(LblIcono)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(LblUserFullname)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MnuFileLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnuFileLogoutActionPerformed
        System.exit(0);
    }//GEN-LAST:event_MnuFileLogoutActionPerformed

    private void MnuFileUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnuFileUsersActionPerformed
        FrmUsers frmUsers = new FrmUsers();
        frmUsers.setVisible(true);
        frmUsers.setLocationRelativeTo(this);
    }//GEN-LAST:event_MnuFileUsersActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar BarMenu;
    private javax.swing.JLabel LblIcono;
    private javax.swing.JLabel LblUserFullname;
    private javax.swing.JMenu MnuFile;
    private javax.swing.JMenuItem MnuFileLogout;
    private javax.swing.JMenuItem MnuFileUsers;
    private javax.swing.JMenu MnuTest;
    private javax.swing.JMenuItem MnuTestResponse;
    private javax.swing.JMenuItem MnuTestSetting;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    // End of variables declaration//GEN-END:variables

}
