
package views;

public class FrmUsers extends javax.swing.JFrame {

    public FrmUsers() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LblTitleUsers = new javax.swing.JLabel();
        MnuBarUsers = new javax.swing.JMenuBar();
        MnuFileUsers = new javax.swing.JMenu();
        MnuCloseUsers = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de evalución");
        setResizable(false);

        LblTitleUsers.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LblTitleUsers.setText("Formulario de Usuarios");

        MnuFileUsers.setText("Archivo");

        MnuCloseUsers.setText("Cerrar");
        MnuCloseUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnuCloseUsersActionPerformed(evt);
            }
        });
        MnuFileUsers.add(MnuCloseUsers);

        MnuBarUsers.add(MnuFileUsers);

        setJMenuBar(MnuBarUsers);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LblTitleUsers)
                .addContainerGap(198, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LblTitleUsers)
                .addContainerGap(246, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MnuCloseUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnuCloseUsersActionPerformed
        this.dispose();
    }//GEN-LAST:event_MnuCloseUsersActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LblTitleUsers;
    private javax.swing.JMenuBar MnuBarUsers;
    private javax.swing.JMenuItem MnuCloseUsers;
    private javax.swing.JMenu MnuFileUsers;
    // End of variables declaration//GEN-END:variables
}
